Unit tests for Surfer class and ControlData class
pyansys/pyprimemesh pull request #353
Opened 2023-01-25 12:28 UTC by AlejandroFernandezLuces

## Explanation
In this PR I implemented more units tests for `pyprimemesh` core functions. The tests added in this PR should cover the following classes: `Surfer`, `ControlData`, `VolumeControl`, `SizeControl`, `PrismControl` and `WrapperControl`. 

I also tried to cover `PeriodicControl` class, but **the creation function for this class is not implemented in the server side**, so this class is essentially not working. 

I would like to have some feedback on the following issues, some of them are probably due to me not knowing how to work with the project.

## Issues found
- I'm not able to test `remesh_face_zonelets_locally` method, since `get_face_zonelets()`
- The method `remesh_face_zonelets` returns the following error: `Not supported for part with topology data`. I'm not sure how can I avoid this error.
- `get_summary()` function for `VolumeControl` is used but it is not defined.
- `PeriodicControl` class cannot be tested because `create_periodic_control()` function is not implemented on server side. Throws the following error: `ansys.meshing.prime.internals.error_handling.PrimeRuntimeError: Could not find method PrimeMesh::ControlData/CreatePeriodicControl`

2023-01-26 20:48 UTC, ninad-kamat commented
The issue with `PeriodicControls` will be resolved. This is a new control that is planned for release in `0.3.0`. I am working on getting the new server for this release updated on Github. I will update you when the new functionality is available as part of the server used in CI.

As far the the issue you faced with remeshing face zonelets, please refer documentation about concepts for how parts are structured in PyPrimeMesh
https://dev.prime.docs.pyansys.com/user_guide/concepts.html

As descibed in the documentation, some of the functionality is available for "Mesh" Parts only. However, the model you are using contains Topology as imported from CAD and hence you will get an error while using "Mesh" Part only functionality.

2023-01-31 18:44 UTC, MaxJPRey submitted a review, later dismissed

2023-02-01 08:00 UTC, RobPasMue requested changes
Overall it's looking good. Thanks for adding the tests. I left some comments, let me know once you've gone through them.

2023-02-01 08:00 UTC, RobPasMue commented on src/ansys/meshing/prime/core/volumecontrol.py
> +        # function get_summary() not implemented
```suggestion
        # TODO: function get_summary() not implemented
```

2023-02-01 08:00 UTC, RobPasMue commented on src/ansys/meshing/prime/core/volumecontrol.py
> +        # function get_summary() not implemented
TODO is typically rendered on another color by most IDEs. It is also a nice way of detecting unimplemented features inside the code quickly. This will make life easier for developers when detecting what remains to be implemented.

2023-02-01 08:00 UTC, RobPasMue commented on tests/core/conftest.py
> +    """
If you are adding a docstring for the fixture, added it completely defined (i.e. parameters section is missing)

2023-02-01 08:00 UTC, RobPasMue commented on tests/core/conftest.py
> +    """
Same as before - include proper docstring.

2023-02-01 08:00 UTC, RobPasMue commented on tests/core/test_controldata.py
> +def test_controldata(initialized_model_elbow):
Break this test down into different unit tests for each of the functionalities you are testing. Also, if there is a failing test, it is better to add a pytest skip decorator rather than leaving the code commented out. At least that way the linter could complain in case the code gets outdated (e.g. class rename, function rename etc)

2023-02-01 08:00 UTC, RobPasMue commented on tests/core/test_surfaceutilities.py
> +import ansys.meshing.prime as prime
Missing module docstring.

2023-02-01 08:00 UTC, RobPasMue commented on tests/core/test_sizecontrol.py
>  import ansys.meshing.prime as prime
Missing module docstring

2023-02-01 08:00 UTC, RobPasMue commented on tests/core/conftest.py
> +import pytest
Missing module docstring

2023-02-01 08:00 UTC, RobPasMue commented on tests/core/test_surfaceutilities.py
> +    assert result.error_code == ErrorCode.NOERROR
When checking against enum values, it is more Pythonic to assert with ``is`` rather than ``==``. Enum values only get instantiated once, so you should be checking that the object itself is indeed the same rather than "==" (this operator can be easily overridden)

2023-02-01 08:00 UTC, RobPasMue commented on tests/core/test_surfer.py
> +def test_mesh_topo_faces(initialized_model_elbow):
You are missing simple test docstrings in all these tests.

2023-02-01 08:00 UTC, RobPasMue commented on tests/core/test_surfer.py
> +    print(face_zonelets)
Please, do not do "print" operations on tests. If you want to check that the ``__repr__`` method works properly for example, just do ``str(object)`` and check that the output is fine.

2023-02-01 11:43 UTC, AlejandroFernandezLuces commented on tests/core/test_surfaceutilities.py
> +import ansys.meshing.prime as prime
Shouldn't this have been stopped by pre-commit? Is this done by https://github.com/pyansys/pyprimemesh/pull/342? If not, I can add the module docstring rule for the pre-commit.

2023-02-01 11:54 UTC, RobPasMue commented on tests/core/test_surfaceutilities.py
> +import ansys.meshing.prime as prime
Nope, this depends on the ``pydocstyle`` hook, which is not implemented. We should consider adding it but it throws back a lot of errors the first time...

2023-02-01 12:06 UTC, AlejandroFernandezLuces commented on tests/core/test_surfer.py
> +    print(face_zonelets)
Missed to remove this print while developing..

2023-02-01 12:15 UTC, AlejandroFernandezLuces commented on tests/core/conftest.py
> +    """
Not sure how to address this, as the parameters for the fixture are other fixtures. You'll never make a call for this fixture using the parameters, so I think that adding them in the documentation will make it more confusing than anything.

2023-02-01 12:54 UTC, RobPasMue commented on tests/core/conftest.py
> +    """
In that case, provide a one-liner docstring without Returns section

2023-02-01 14:30 UTC, AlejandroFernandezLuces commented on tests/core/test_surfaceutilities.py
> +import ansys.meshing.prime as prime
If it implies a lot of changes the first time it's best to leave it for its own PR then.

2023-02-06 21:08 UTC, MaxJPRey commented on tests/core/test_controldata.py
> +    controldata = model.control_data
Can we rename this variable `control_data` if possible or will it create any conflicts with other variables sharing a similar name?
```suggestion
    control_data = model.control_data
```

2023-02-07 12:05 UTC, AlejandroFernandezLuces commented on tests/core/test_surfaceutilities.py
> +import ansys.meshing.prime as prime
Opened a new issue for this https://github.com/pyansys/pyprimemesh/issues/370

2023-02-07 20:54 UTC, MaxJPRey approved these changes

2023-02-07 23:19 UTC, ninad-kamat commented
@AlejandroFernandezLuces I have pushed changes to use the new `23.1.1` server in our CI. This means newer features like Periodic Controls etc should be working now. Could you update your branch and try if these do work?

2023-02-15 11:22 UTC, AlejandroFernandezLuces commented
> @AlejandroFernandezLuces I have pushed changes to use the new `23.1.1` server in our CI. This means newer features like Periodic Controls etc should be working now. Could you update your branch and try if these do work?

Solved this, all done on my side @ninad-kamat

2023-03-10 18:55 UTC, ninad-kamat approved these changes

2023-03-27 20:19 UTC, MaxJPRey commented
@RobPasMue You requested some changes. The PR is now ready.

2023-03-27 20:23 UTC, RobPasMue approved these changes
LGTM!! Sorry I missed it!

2023-03-28 16:12 UTC, merged